name: trivy scans

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/trivy-scans.yml'
      - '.trivyignore'

concurrency:
  group: trivy-scans-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  trivy-fs-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run trivy filesystem scan
        uses: aquasecurity/trivy-action@0.9.2
        with:
          scan-type: 'fs'
          scan-ref: '.'
          skip-dirs: 'docs'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true